
[build]
publish = "dist"
command = "pnpm run build"

[build.environment]
NODE_VERSION = "20"
PLAYWRIGHT_BROWSERS_PATH = "0"


[[redirects]]
from = "/2023/github-notifications/src"
to = "https://github.com/antfu/talks/tree/main/2023-05-17"
status = 302

[[redirects]]
from = "2023-05-17"
to = "https://talks.antfu.me/2023/github-notifications/"
status = 301

[[redirects]]
from = "/2023/github-notifications/*"
to = "/2023/github-notifications/index.html"
status = 200

[[redirects]]
from = "/2023/nuxt-devtools-strasbourg/src"
to = "https://github.com/antfu/talks/tree/main/2023-05-25"
status = 302

[[redirects]]
from = "2023-05-25"
to = "https://talks.antfu.me/2023/nuxt-devtools-strasbourg/"
status = 301

[[redirects]]
from = "/2023/nuxt-devtools-strasbourg/*"
to = "/2023/nuxt-devtools-strasbourg/index.html"
status = 200

[[redirects]]
from = "/2024/vue-js-training/pdf"
to = "https://github.com/antfu/talks/blob/main/2024-08-18/2023-05-25-nuxt-devtools-strasbourg-en.pdf?raw=true"
status = 302

[[redirects]]
from = "/2024-08-18/pdf"
to = "https://github.com/antfu/talks/blob/main/2024-08-18/2023-05-25-nuxt-devtools-strasbourg-en.pdf?raw=true"
status = 302

[[redirects]]
from = "/2024/vue-js-training/src"
to = "https://github.com/antfu/talks/tree/main/2024-08-18"
status = 302

[[redirects]]
from = "2024-08-18"
to = "https://talks.antfu.me/2024/vue-js-training/"
status = 301

[[redirects]]
from = "/2024/vue-js-training/*"
to = "/2024/vue-js-training/index.html"
status = 200

[[redirects]]
from = "/"
to = "https://kathirr007-web-trainings.netlify.app"
status = 302
